# Run CI for R using https://eddelbuettel.github.io/r-ci/
# This file is a slight variant by running a matrix of containers

name: ci

on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependency
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev libdeflate-dev
          echo 'export LIBRARY_PATH=${LIBRARY_PATH}:/usr/lib/x84_64-linux-gnu' >> ~/.bashrc
          echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/x84_64-linux-gnu' >> ~/.bashrc

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        
